# Generated by Django 3.0 on 2021-01-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='style_value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
