# Generated by Django 3.0 on 2021-01-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_style_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='satchel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
