# Generated by Django 3.0 on 2021-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='satchel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
