# Generated by Django 3.0 on 2021-01-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210110_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='superanons.png', null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
