# Generated by Django 3.0 on 2021-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210112_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='satchel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
