# Generated by Django 3.0 on 2021-01-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_matrix',
            field=models.CharField(blank=True, default='-timestamp', max_length=70, null=True),
        ),
    ]
