# Generated by Django 3.0 on 2021-01-02 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocket',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='pocket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
