# Generated by Django 3.0 on 2021-01-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0004_auto_20210106_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pocket Price'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='A Description'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTime of Creation'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Pocket Name'),
        ),
    ]
