# Generated by Django 3.0 on 2021-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0005_auto_20210108_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pocket Price'),
        ),
    ]
