# Generated by Django 3.0 on 2021-01-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0007_auto_20210114_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='category',
            field=models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Recreation | Entertainment', 'Recreation | Entertainment'), ('Personal Spending', 'Personal Spending'), ('Investments ( Stocks, Bonds ,Etc.)', 'Investments ( Stocks, Bonds ,Etc.)'), ('Medical | Healthcare', 'Medical | Healthcare'), ('Insurance', 'Insurance'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Housing', 'Housing')], default='Miscellaneous', max_length=27, verbose_name='current Category'),
        ),
    ]
