# Generated by Django 3.0 on 2021-01-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0009_auto_20210118_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocket',
            options={},
        ),
    ]
