# Generated by Django 3.0 on 2021-01-19 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0010_auto_20210118_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='pocket_time_instance',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 22, 7, 31, 78889, tzinfo=utc), verbose_name='DateTime of Expense Instance'),
            preserve_default=False,
        ),
    ]
