# Generated by Django 3.0 on 2021-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0012_auto_20210123_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='timestamp',
            field=models.DateField(auto_now_add=True, verbose_name='DateTime of Creation'),
        ),
    ]
