# Generated by Django 3.0 on 2021-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0013_auto_20210128_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='pocket_time_instance',
            field=models.DateField(verbose_name='Exact Date & Time of Pocket '),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DateTime of Creation'),
        ),
    ]
